<a href="https://colab.research.google.com/github/t1mmy89ru/nyu-python-public-policy/blob/master/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [24]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive

In [30]:
df = pd.read_csv('/content/drive/My Drive/Data for Python/311_Service_Requests_2018-19.csv',header='infer')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (8,17,20,31,34) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [31]:
df

         Unique Key  ...                                 Location
0          39888071  ...   (40.79333937834769, -73.9429417746998)
1          39889166  ...   (40.82012422332215, -73.9530712339799)
2          39882869  ...   (40.67080917938279, -73.9513990916184)
3          39894246  ...  (40.74026158873342, -73.99051651686905)
4          39881329  ...  (40.68814402968042, -73.75098958473612)
...             ...  ...                                      ...
2859195    43619262  ...   (40.87970084316435, -73.9010571445122)
2859196    43622052  ...  (40.70178323733244, -73.92055493919345)
2859197    43625918  ...   (40.66999185896368, -73.9224889475533)
2859198    43622055  ...                                      NaN
2859199    43623704  ...  (40.63679359185655, -74.15397942810047)

[2859200 rows x 41 columns]

In [41]:
df['Created Date'].max()

'12/31/2018 12:59:41 PM'

In [39]:
df['Created Date'].min()

01/01/2019 01:00:00 PM

In [42]:
type(df['Created Date'])

pandas.core.series.Series

In [0]:
#The date pulled through the max function is a year earlier (i.e., less) than the date pulled through the min function

In [47]:
df.tail(1)

         Unique Key  ...                                 Location
2859199    43623704  ...  (40.63679359185655, -74.15397942810047)

[1 rows x 41 columns]

In [0]:
df.head(1)

   Unique Key  ...                                Location
0    39888071  ...  (40.79333937834769, -73.9429417746998)

[1 rows x 41 columns]

In [0]:
#How do we subset data on different conditions?